[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "recruitment.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
addopts = [
    "--no-migrations",
    "--ignore=test-results",
    "--disable-warnings",
]
[tool.black]
line-length = 79